CREATE VIEW EMPLOYMENT_HISTORY AS
SELECT 
    JH.EMP_ID,
    CONCAT(E.F_NAME, ' ', E.L_NAME) AS EMPLOYEE_NAME,
    JH.START_DATE,
    JH.END_DATE,
    OLD_J.JOB_TITLE AS PREVIOUS_JOB,
    NEW_J.JOB_TITLE AS NEW_JOB,
    D.DEP_NAME AS DEPARTMENT
FROM JOB_HISTORY JH
JOIN EMPLOYEES E ON JH.EMP_ID = E.EMP_ID
JOIN JOBS OLD_J ON JH.JOB_ID = OLD_J.JOB_IDENT
JOIN JOBS NEW_J ON E.JOB_ID = NEW_J.JOB_IDENT
JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP
ORDER BY JH.EMP_ID, JH.START_DATE;