-- Create an updatable view
CREATE VIEW EMPLOYEE_BASIC_INFO AS
SELECT EMP_ID, F_NAME, L_NAME, DEP_ID
FROM EMPLOYEES
WHERE DEP_ID IS NOT NULL;

-- You can update through this view
UPDATE EMPLOYEE_BASIC_INFO 
SET L_NAME = 'Smith' 
WHERE EMP_ID = 100;