CREATE VIEW HIGH_SALARY_EMPLOYEES AS
SELECT * FROM EMPLOYEES
WHERE SALARY > 50000
WITH CHECK OPTION;

-- This will fail because it would remove row from view
UPDATE HIGH_SALARY_EMPLOYEES 
SET SALARY = 40000 
WHERE EMP_ID = 100;  -- ERROR!