-- Add a new column to the view
CREATE OR REPLACE VIEW EMPLOYEE_SALARY_SUMMARY AS
SELECT 
    DEP_ID,
    COUNT(*) AS NUM_EMPLOYEES,
    AVG(SALARY) AS AVG_SALARY,
    MAX(SALARY) AS MAX_SALARY,
    MIN(SALARY) AS MIN_SALARY,
    SUM(SALARY) AS TOTAL_SALARY  -- Added column
FROM EMPLOYEES
GROUP BY DEP_ID;