CREATE OR REPLACE VIEW HIGH_EARNERS AS
SELECT 
    E.*,
    D.DEP_NAME,
    (SELECT AVG(SALARY) FROM EMPLOYEES) AS COMPANY_AVG
FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP
WHERE E.SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);