CREATE VIEW EMPLOYEE_SALARY_SUMMARY AS
SELECT 
    DEP_ID,
    COUNT(*) AS NUM_EMPLOYEES,
    AVG(SALARY) AS AVG_SALARY,
    MAX(SALARY) AS MAX_SALARY,
    MIN(SALARY) AS MIN_SALARY
FROM EMPLOYEES
GROUP BY DEP_ID;