CREATE VIEW DEPARTMENT_PERFORMANCE AS
SELECT 
    D.DEPT_ID_DEP AS DEPT_ID,
    D.DEP_NAME,
    COUNT(E.EMP_ID) AS EMPLOYEE_COUNT,
    ROUND(AVG(E.SALARY), 2) AS AVG_SALARY,
    MIN(E.SALARY) AS MIN_SALARY,
    MAX(E.SALARY) AS MAX_SALARY,
    SUM(E.SALARY) AS TOTAL_PAYROLL
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPT_ID_DEP = E.DEP_ID
GROUP BY D.DEPT_ID_DEP, D.DEP_NAME
ORDER BY AVG_SALARY DESC;