-- Create a public directory view
CREATE VIEW EMPLOYEE_DIRECTORY AS
SELECT 
    E.EMP_ID,
    CONCAT(E.F_NAME, ' ', E.L_NAME) AS FULL_NAME,
    D.DEP_NAME AS DEPARTMENT,
    J.JOB_TITLE AS POSITION,
    CONCAT(M.F_NAME, ' ', M.L_NAME) AS MANAGER_NAME
FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON E.DEP_ID = D.DEPT_ID_DEP
LEFT JOIN JOBS J ON E.JOB_ID = J.JOB_IDENT
LEFT JOIN EMPLOYEES M ON E.MANAGER_ID = M.EMP_ID;