USE HR;
SELECT * FROM `EMPLOYEES` LIMIT 5;
SELECT * FROM `DEPARTMENTS` LIMIT 5;
SELECT * FROM `JOBS` LIMIT 5;
SELECT * FROM `LOCATIONS` LIMIT 5;
SELECT * FROM `JOB_HISTORY` LIMIT 5;


{# 
-- First, ensure you're in HR database
USE HR;

-- Test each table with backticks
SELECT '=== EMPLOYEES ===' AS '';
SELECT * FROM `EMPLOYEES` LIMIT 3;

SELECT '\n=== DEPARTMENTS ===' AS '';
SELECT * FROM `DEPARTMENTS` LIMIT 3;

SELECT '\n=== JOBS ===' AS '';
SELECT * FROM `JOBS` LIMIT 3;

SELECT '\n=== LOCATIONS ===' AS '';
SELECT * FROM `LOCATIONS` LIMIT 3;

SELECT '\n=== JOB_HISTORY ===' AS '';
SELECT * FROM `JOB_HISTORY` LIMIT 3; #}