DELIMITER //
CREATE PROCEDURE GENERATE_SALES_REPORT(
    IN start_date DATE,
    IN end_date DATE
)
BEGIN
    -- Daily sales summary
    SELECT 
        SALEDATE,
        PET,
        COUNT(*) AS PETS_SOLD,
        SUM(SALEPRICE) AS TOTAL_REVENUE,
        AVG(SALEPRICE) AS AVG_PRICE
    FROM PETSALE
    WHERE SALEDATE BETWEEN start_date AND end_date
    GROUP BY SALEDATE, PET
    ORDER BY SALEDATE DESC, TOTAL_REVENUE DESC;
    
    -- Category summary
    SELECT 
        PET,
        COUNT(*) AS TOTAL_SOLD,
        SUM(SALEPRICE) AS CATEGORY_REVENUE,
        ROUND(SUM(SALEPRICE) * 100.0 / (SELECT SUM(SALEPRICE) FROM PETSALE WHERE SALEDATE BETWEEN start_date AND end_date), 2) AS REVENUE_PERCENT
    FROM PETSALE
    WHERE SALEDATE BETWEEN start_date AND end_date
    GROUP BY PET
    ORDER BY CATEGORY_REVENUE DESC;
    
    -- Best selling day
    SELECT 
        SALEDATE,
        SUM(SALEPRICE) AS DAILY_REVENUE
    FROM PETSALE
    WHERE SALEDATE BETWEEN start_date AND end_date
    GROUP BY SALEDATE
    ORDER BY DAILY_REVENUE DESC
    LIMIT 1;
END //
DELIMITER ;