-- Practice SQL
-- Database: SanFranciscoFilmLocations

-- Query 1: Select all records from FilmLocations table
SELECT * FROM FilmLocations;

/*
Expected Results (first 50 rows shown):
+------------------------------+-------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------+-----------------------------+------------------------+----------------------------------------------------+----------------+------------------+----------------+
| Title                        | ReleaseYear | Locations                                         | FunFacts                                                                                             | ProductionCompany                                 | Distributor                 | Director               | Writer                                             | Actor1         | Actor2           | Actor3         |
+------------------------------+-------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------+-----------------------------+------------------------+----------------------------------------------------+----------------+------------------+----------------+
| 180                          | 2011        | Epic Roasthouse (399 Embarcadero)                 |                                                                                                      | SPI Cinemas                                       |                             | Jayendra               | Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba   | Siddarth       | Nithya Menon     | Priya Anand    |
| 180                          | 2011        | Mason & California Streets (Nob Hill)             |                                                                                                      | SPI Cinemas                                       |                             | Jayendra               | Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba   | Siddarth       | Nithya Menon     | Priya Anand    |
| 180                          | 2011        | Justin Herman Plaza                               |                                                                                                      | SPI Cinemas                                       |                             | Jayendra               | Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba   | Siddarth       | Nithya Menon     | Priya Anand    |
| 180                          | 2011        | 200 block Market Street                           |                                                                                                      | SPI Cinemas                                       |                             | Jayendra               | Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba   | Siddarth       | Nithya Menon     | Priya Anand    |
| 180                          | 2011        | City Hall                                         |                                                                                                      | SPI Cinemas                                       |                             | Jayendra               | Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba   | Siddarth       | Nithya Menon     | Priya Anand    |
| 180                          | 2011        | Polk & Larkin Streets                             |                                                                                                      | SPI Cinemas                                       |                             | Jayendra               | Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba   | Siddarth       | Nithya Menon     | Priya Anand    |
| 180                          | 2011        | Randall Museum                                    |                                                                                                      | SPI Cinemas                                       |                             | Jayendra               | Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba   | Siddarth       | Nithya Menon     | Priya Anand    |
| 180                          | 2011        | 555 Market St.                                    |                                                                                                      | SPI Cinemas                                       |                             | Jayendra               | Umarji Anuradha, Jayendra, Aarthi Sriram, & Suba   | Siddarth       | Nithya Menon     | Priya Anand    |
| 24 Hours on Craigslist       | 2005        |                                                   |                                                                                                      | Yerba Buena Productions                           | Zealot Pictures             | Michael Ferris Gibson  | N/A                                                | Craig Newmark  |                  |                |
| A Night Full of Rain         | 1978        | Embarcadero Freeway                               | Embarcadero Freeway, which was featured in the film was demolished in 1989 because of structural damage from the 1989 Loma Prieta Earthquake) | Liberty Film                                      | Warner Bros. Pictures       | Lina Wertmuller        | Lina Wertmuller                                     | Candice Bergen | Giancarlo Gianni |                |
| A Night Full of Rain         | 1978        | Fairmont Hotel (950 Mason Street, Nob Hill)       | In 1945 the Fairmont hosted the United Nations Conference on International Organization as delegates arrived to draft a charter for the organization. The U.S. Secretary of State, Edward Stettinius drafted the charter in the hotel's Garden Room. | Liberty Film | Warner Bros. Pictures | Lina Wertmuller | Lina Wertmuller                                  | Candice Bergen | Giancarlo Gianni |                |
| A Night Full of Rain         | 1978        | San Francisco Chronicle (901 Mission Street at 15th Street) | The San Francisco Zodiac Killer of the late 1960s sent his notes and letters to the Chronicle's offices. | Liberty Film                                      | Warner Bros. Pictures       | Lina Wertmuller        | Lina Wertmuller                                     | Candice Bergen | Giancarlo Gianni |                |
| A Night Full of Rain         | 1978        | Broadway (North Beach)                            |                                                                                                      | Liberty Film                                      | Warner Bros. Pictures       | Lina Wertmuller        | Lina Wertmuller                                     | Candice Bergen | Giancarlo Gianni |                |
| About a Boy                  | 2014        | Broderick from Fulton to McAlister                |                                                                                                      | NBC Studios                                       | National Broadcasting Company | Mark J. Kunerth        | Jason Katims                                        | David Walton   | Minnie Driver    |                |
| About a Boy                  | 2014        | Crissy Field                                      |                                                                                                      | NBC Studios                                       | National Broadcasting Company | Mark J. Kunerth        | Jason Katims                                        | David Walton   | Minnie Driver    |                |
| About a Boy                  | 2014        | Powell from Bush and Sutter                       |                                                                                                      | NBC Studios                                       | National Broadcasting Company | Mark J. Kunerth        | Jason Katims                                        | David Walton   | Minnie Driver    |                |
| Age of Adaline               | 2015        | Pier 50- end of the pier                          |                                                                                                      | Lionsgate / Sidney Kimmel Entertainment / Lakeshore Entertainment |                         | Lee Toland Krieger      | J. Mills Goodloe                                     | Blake Lively   | Harrison Ford    | Ellen Burstyn  |
| Age of Adaline               | 2015        | California @ Montgomery                           |                                                                                                      | Lionsgate / Sidney Kimmel Entertainment / Lakeshore Entertainment |                         | Lee Toland Krieger      | J. Mills Goodloe                                     | Blake Lively   | Harrison Ford    | Ellen Burstyn  |
| Age of Adaline               | 2015        | Montgomery/Green                                  |                                                                                                      | Lionsgate / Sidney Kimmel Entertainment / Lakeshore Entertainment |                         | Lee Toland Krieger      | J. Mills Goodloe                                     | Blake Lively   | Harrison Ford    | Ellen Burstyn  |
| Age of Adaline               | 2015        | Driving various SF Streets                        |                                                                                                      | Lionsgate / Sidney Kimmel Entertainment / Lakeshore Entertainment |                         | Lee Toland Krieger      | J. Mills Goodloe                                     | Blake Lively   | Harrison Ford    | Ellen Burstyn  |
| Age of Adaline               | 2015        | Plate Shots SF streets various                    |                                                                                                      | Lionsgate / Sidney Kimmel Entertainment / Lakeshore Entertainment |                         | Lee Toland Krieger      | J. Mills Goodloe                                     | Blake Lively   | Harrison Ford    | Ellen Burstyn  |
| After the Thin Man           | 1936        | Coit Tower                                        | The Tower was funded by a gift bequeathed by Lillie Hitchcock Coit, a socialite who reportedly liked to chase fires. Though the tower resembles a firehose nozzle, it was not designed this way. | Metro-Goldwyn Mayer                               | Metro-Goldwyn Mayer          | W.S. Van Dyke          | Frances Goodrich                                     | William Powell | Myrna Loy        | James Stewart  |
| Ant-Man                      | 2015        | California between Kearney and Davis              | Driving shots                                                                                        | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
| Americana                    | 2015        | St. Francis Episcopal Church (399 San Fernando Way) |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Romolo Place @ Fresno St.                         |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Palace of Fine Arts                               |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | John Shelley Drive John McLaren Park              |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Treasure Island                                   |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | The San Francisco School (300 Gavin St.)          |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | 33 Spruce St                                      |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Coi Restaurant (373 Broadway)                     |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Foreign Cinema (2534 Mission)                     |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Bernal Heights Park                               |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Jackson St. at Spruce                             |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | 679 Madrid St                                     |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Roxie Theater (3117 16th St.)                     |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Variety Preview Room (582 Market St.)             |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | Laguna Honda Hospital; 375 Laguna Honda Blvd.     |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | 3232 Jackson Ave.                                 |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Americana                    | 2015        | 20th St and Illinois/Faxon St. and Kenwood/Glenbrook at Mt. Springs |                                                                                                      | Sutro Films LLC                                   |                             | Zachary Shedd          | Zachary Shedd                                        | Kelli Garner   | Jack Davenport   | Peter Coyote   |
| Another 48 Hours             | 1990        |                                                   |                                                                                                      | Eddie Murphy Productions                          | Paramount Pictures           | Walter Hill            | Walter Hill                                         | Eddie Murphy   | Nick Nolte       |                |
| Ant-Man                      | 2015        | Conzelman Rd at McCollough Rd and down Conzelman Rd. | Aerial shots                                                                                     | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
| Ant-Man                      | 2015        | Lombard at Hyde                                   |                                                                                                      | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
| Ant-Man                      | 2015        | 601 Buena Vista Ave West at Java St.              |                                                                                                      | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
| Ant-Man                      | 2015        | 420 Jones St. at Ellis St.                        |                                                                                                      | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
| Ant-Man                      | 2015        | Broadway between Powell and Davis                 | Driving shots                                                                                        | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
| Ant-Man                      | 2015        | Columbus between Bay and Washington               | Driving shots                                                                                        | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
| Ant-Man                      | 2015        | Pine between Kearney and Davis                    | Driving shots                                                                                        | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
| Ant-Man                      | 2015        | Market between Stuart and Van Ness                | Driving shots                                                                                        | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
| Ant-Man                      | 2015        | Grant between Bush and Broadway                   | Driving shots                                                                                        | PYM Particles Productions, LLC                    | Walt Disney Studios Motion Pictures | Peyton Reed            | Gabriel Ferrari                                     | Michael Douglas | Paul Rudd        |                |
+------------------------------+-------------+---------------------------------------------------+------------------------------------------------------------------------------------------------------+---------------------------------------------------+-----------------------------+------------------------+----------------------------------------------------+----------------+------------------+----------------+
(3414 total rows, 3364 rows hidden in truncated output)

Table Schema:
- Title: Film title
- ReleaseYear: Year the film was released
- Locations: Filming locations in San Francisco
- FunFacts: Interesting facts about the locations/filming
- ProductionCompany: Company that produced the film
- Distributor: Company that distributed the film
- Director: Film director
- Writer: Film writer(s)
- Actor1, Actor2, Actor3: Main actors in the film
*/

-- File name: select_all_film_locations.sql

-- Additional analysis queries:
-- 1. Count total number of films (unique titles)
-- SELECT COUNT(DISTINCT Title) as UniqueFilms FROM FilmLocations;

-- 2. Films with the most filming locations
-- SELECT Title, COUNT(*) as LocationCount FROM FilmLocations GROUP BY Title ORDER BY LocationCount DESC LIMIT 10;

-- 3. Most common filming locations
-- SELECT Locations, COUNT(*) as FilmCount FROM FilmLocations WHERE Locations != '' GROUP BY Locations ORDER BY FilmCount DESC LIMIT 10;

-- 4. Year with most filmed locations
-- SELECT ReleaseYear, COUNT(*) as LocationCount FROM FilmLocations GROUP BY ReleaseYear ORDER BY LocationCount DESC LIMIT 10;

-- 5. Films with fun facts
-- SELECT Title, Locations, FunFacts FROM FilmLocations WHERE FunFacts != '' ORDER BY Title;