-- MySQL doesn't have ALTER PROCEDURE for logic changes
-- Must drop and recreate
DROP PROCEDURE IF EXISTS RETRIEVE_ALL;
CREATE PROCEDURE RETRIEVE_ALL()
BEGIN
    SELECT ID, PET, SALEPRICE, SALEDATE FROM PETSALE;
END;