-- View 1: Employee Demographics
CREATE VIEW HR_EMPLOYEE_DEMOGRAPHICS AS
SELECT 
    DEP_ID,
    SEX,
    COUNT(*) AS COUNT,
    AVG(YEAR(CURDATE()) - YEAR(B_DATE)) AS AVG_AGE
FROM EMPLOYEES
GROUP BY DEP_ID, SEX;

-- View 2: Salary Distribution
CREATE VIEW HR_SALARY_DISTRIBUTION AS
SELECT 
    DEP_ID,
    CASE 
        WHEN SALARY < 40000 THEN 'Under 40K'
        WHEN SALARY BETWEEN 40000 AND 60000 THEN '40K-60K'
        WHEN SALARY BETWEEN 60001 AND 80000 THEN '60K-80K'
        ELSE 'Over 80K'
    END AS SALARY_BAND,
    COUNT(*) AS EMPLOYEE_COUNT
FROM EMPLOYEES
GROUP BY DEP_ID, SALARY_BAND;

-- View 3: Department Headcount Trends
CREATE VIEW HR_DEPARTMENT_TRENDS AS
SELECT 
    D.DEP_NAME,
    COUNT(E.EMP_ID) AS CURRENT_HEADCOUNT,
    (SELECT COUNT(*) FROM JOB_HISTORY JH 
     WHERE JH.DEPT_ID = D.DEPT_ID_DEP 
     AND JH.END_DATE >= DATE_SUB(CURDATE(), INTERVAL 1 YEAR)) AS HIRES_LAST_YEAR
FROM DEPARTMENTS D
LEFT JOIN EMPLOYEES E ON D.DEPT_ID_DEP = E.DEP_ID
GROUP BY D.DEPT_ID_DEP, D.DEP_NAME;